server:
  rootPath: /api/*
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8443

logging:
  level: DEBUG

mongodb:
  host: 192.168.99.100
  port: 27017
  username: null
  password: null