server:
  rootPath: /api/*
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8443

logging:
  level: INFO

mongodb:
  host: 192.168.99.100
  port: 32775


api:
  foursquare:
    client_id: null
    client_secret: null